### ISSUE TITLE
Group feature not working along with buttons to group

### ISSUE THREAD

**Issue by DraculaPB** [ghostscript3r/poe-trade-enhancer#2]
![](https://i.imgur.com/36ER3fJ.png)
![](https://i.imgur.com/mU2MIjO.png)

Only red text I've found

**Comment by ghostscript3r** [comment]
Didn't have the time to work on this yet, but it might be not working because you didn't give the script permission to contact poe.ninja. I know it should work almost the same, but I didn't pay much attention to how it works without that permission because I didn't think many would have used it without that.

I'll dig deeper in a few hours, but forst two questions:
Did you not give permission on purpose or tampermonkey never asked for it in the first place?
If you did, do you know how to revert so you can try if it works for you with that permission?

**Comment by DraculaPB** [comment]
It never asked at all.

**Comment by ghostscript3r** [comment]
Can you try to add this line at line 8 of the script and see if it works then
// @connect poe.ninja
don't delete anything just add this line

**Comment by DraculaPB** [comment]
> Can you try to add this line at line 8 of the script and see if it works then
> // @connect poe.ninja
> don't delete anything just add this line

Did not work, however... Installing tapermonkey BETA fixes something. The script now runs.

**Comment by ghostscript3r** [comment]
browser?

**Comment by DraculaPB** [comment]
> browser?

Chrome

**Comment by ghostscript3r** [comment]
This might be an issue with tampermonkey settings. For example in various tests I once erroneously clicked not to load data from poe.ninja, and never ask again. I haven't been able to find anywhere in settings how to reset this, and eneded up resetting TM to factory (advanced settings).
If you can try to do that too. Be ware that you'll have to reinstall all your script after that.

**Comment by DraculaPB** [comment]
That seems to do it ;)
