### ISSUE TITLE
Unable to Click on Whisper

### ISSUE THREAD

**Issue by Arcadium** [ghostscript3r/poe-trade-enhancer#5]
When clicking on whisper it doesn't copy the automatic message for me. Used to be working fine.

**Comment by ghostscript3r** [comment]
Can you add a screenshot and maybe a screenshot of your console logs? Any detail you can provide is important. Which browser? Which version of the script?
If this happens when you multi live search starting from an empty search form you probably just need to update the script to latest version, 1.2.37

**Comment by Arcadium** [comment]
Heya,

That was exactly the problem. Its fixed now then.

**Comment by ghostscript3r** [comment]
glad :)
